[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.1"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs" 