// بيانات وهمية للاستخدام عند فشل الاتصال بقاعدة البيانات

import { useTranslation } from 'react-i18next';

const { t } = useTranslation();

export const mockData = {
  employees: [
    {
      id: 1,
      name: t('employees.name'),
      department: t('employees.department'),
      position: t('employees.position'),
      hire_date: t('employees.hire_date'),
      fingerprint_id: "1001",
      active_status: t('employees.active_status'),
      email: "ahmed@example.com",
      phone: "0501234567",
      address: "الرياض، السعودية",
      national_id: "1234567890",
    },
    {
      id: 2,
      name: t('employees.name'),
      department: t('employees.department'),
      position: t('employees.position'),
      hire_date: t('employees.hire_date'),
      fingerprint_id: "1002",
      active_status: t('employees.active_status'),
      email: "sara@example.com",
      phone: "0507654321",
      address: "جدة، السعودية",
      national_id: "0987654321",
    },
    {
      id: 3,
      name: t('employees.name'),
      department: t('employees.department'),
      position: t('employees.position'),
      hire_date: t('employees.hire_date'),
      fingerprint_id: "1003",
      active_status: t('employees.active_status'),
      email: "mohammed@example.com",
      phone: "0551234567",
      address: "الدمام، السعودية",
      national_id: "1122334455",
    },
  ],
  attendance: [
    {
      id: 1,
      employee_id: 1,
      employee: {
        id: 1,
        name: t('employees.name'),
        department: t('employees.department'),
        position: t('employees.position'),
      },
      check_in: "2023-05-01T08:00:00",
      check_out: "2023-05-01T17:00:00",
      date: "2023-05-01",
      status: t('attendance.type'),
      late_minutes: 0,
      overtime_minutes: 0,
    },
    {
      id: 2,
      employee_id: 2,
      employee: {
        id: 2,
        name: t('employees.name'),
        department: t('employees.department'),
        position: t('employees.position'),
      },
      check_in: "2023-05-01T08:15:00",
      check_out: "2023-05-01T17:00:00",
      date: "2023-05-01",
      status: t('attendance.type'),
      late_minutes: 15,
      overtime_minutes: 0,
    },
    {
      id: 3,
      employee_id: 3,
      employee: {
        id: 3,
        name: t('employees.name'),
        department: t('employees.department'),
        position: t('employees.position'),
      },
      check_in: "2023-05-01T08:05:00",
      check_out: "2023-05-01T17:30:00",
      date: "2023-05-01",
      status: t('attendance.type'),
      late_minutes: 5,
      overtime_minutes: 30,
    },
  ],
  leaves: [
    {
      id: 1,
      employee_id: 1,
      employee: {
        id: 1,
        name: t('employees.name'),
        department: t('employees.department'),
        position: t('employees.position'),
      },
      start_date: "2023-06-01",
      end_date: "2023-06-05",
      reason: t('leave_requests.type'),
      status: "pending",
      created_at: "2023-05-15T10:00:00",
    },
    {
      id: 2,
      employee_id: 2,
      employee: {
        id: 2,
        name: t('employees.name'),
        department: t('employees.department'),
        position: t('employees.position'),
      },
      start_date: "2023-06-10",
      end_date: "2023-06-15",
      reason: t('leave_requests.type'),
      status: "approved",
      approved_by: 3,
      approved_at: "2023-05-16T14:00:00",
      created_at: "2023-05-16T10:00:00",
    },
  ],
  devices: [
    {
      id: 1,
      name: t('devices.name'),
      location: "المدخل الرئيسي",
      ip_address: "192.168.1.100",
      port: 4370,
      status: t('devices.status'),
      last_sync: "2023-05-01T08:00:00",
    },
    {
      id: 2,
      name: t('devices.name'),
      location: "مدخل الموظفين",
      ip_address: "192.168.1.101",
      port: 4370,
      status: t('devices.status'),
      last_sync: "2023-04-30T17:00:00",
    },
  ],
  stats: {
    today: {
      present: 25,
      absent: 3,
      late: 2,
      onLeave: 1,
    },
    month: {
      present: 550,
      absent: 30,
      late: 15,
      onLeave: 5,
    },
  },
}
